export interface CubeData {
  companySize: 'large' | 'middle'
  type: 'core' | 'small' | 'edge'
  cpu: number
  percent: number
  height?: number
  max?: number
  labelSize?: number
  textSize?: number
}

export const ESC_SIZE: Record<'mysql', CubeData[]> = {
  mysql: [
    {
      companySize: 'large',
      type: 'core',
      cpu: 32,
      percent: 45,
      height: 1,
      labelSize: 16,
      textSize: 24,
    },
    {
      companySize: 'large',
      type: 'core',
      cpu: 16,
      percent: 20,
      height: 0.75,
      labelSize: 16,
      textSize: 24,
    },
    {
      companySize: 'large',
      type: 'small',
      cpu: 8,
      percent: 10,
      labelSize: 16,
      textSize: 16,
    },
    {
      companySize: 'large',
      type: 'small',
      cpu: 8,
      percent: 15,
      labelSize: 16,
      textSize: 16,
    },
    {
      companySize: 'large',
      type: 'small',
      cpu: 8,
      percent: 20,
      labelSize: 16,
      textSize: 16,
    },
    {
      companySize: 'large',
      type: 'edge',
      cpu: 4,
      percent: 7,
      labelSize: 10,
      textSize: 14,
    },
    {
      companySize: 'large',
      type: 'edge',
      cpu: 4,
      percent: 8,
      labelSize: 10,
      textSize: 14,
    },
    {
      companySize: 'large',
      type: 'edge',
      cpu: 4,
      percent: 9,
      labelSize: 10,
      textSize: 14,
    },
    {
      companySize: 'large',
      type: 'edge',
      cpu: 4,
      percent: 13,
      labelSize: 10,
      textSize: 14,
    },
    {
      companySize: 'middle',
      type: 'core',
      cpu: 16,
      percent: 25,
      height: 1,
      labelSize: 16,
      textSize: 24,
    },
    {
      companySize: 'middle',
      type: 'core',
      cpu: 8,
      percent: 30,
      height: 0.65,
      labelSize: 16,
      textSize: 24,
    },
    {
      companySize: 'middle',
      type: 'small',
      cpu: 4,
      percent: 35,
      labelSize: 16,
      textSize: 16,
    },
    {
      companySize: 'middle',
      type: 'small',
      cpu: 4,
      percent: 25,
      labelSize: 16,
      textSize: 16,
    },
    {
      companySize: 'middle',
      type: 'edge',
      cpu: 2,
      percent: 5,
      labelSize: 10,
      textSize: 16,
    },
    {
      companySize: 'middle',
      type: 'edge',
      cpu: 2,
      percent: 6,
      labelSize: 10,
      textSize: 16,
    },
    {
      companySize: 'middle',
      type: 'edge',
      cpu: 2,
      percent: 7,
      labelSize: 10,
      textSize: 16,
    },
    {
      companySize: 'middle',
      type: 'edge',
      cpu: 2,
      percent: 8,
      labelSize: 10,
      textSize: 16,
    },
    {
      companySize: 'middle',
      type: 'edge',
      cpu: 2,
      percent: 9,
      labelSize: 10,
      textSize: 16,
    },
  ],
}

export const OB_SIZE: Record<'cluster' | 'tenant', CubeData[]> = {
  cluster: [
    { companySize: 'middle', cpu: 29, percent: 32.76, type: 'core' },
    { companySize: 'large', cpu: 64, percent: 35.44, type: 'core' },
  ],
  tenant: [
    { companySize: 'middle', percent: 100, type: 'core', cpu: 13, height: 1 },
    { companySize: 'middle', percent: 100, type: 'core', cpu: 6, height: 0.75 },
    { companySize: 'middle', percent: 100, type: 'small', cpu: 3 },
    { companySize: 'middle', percent: 100, type: 'small', cpu: 3 },
    { companySize: 'middle', percent: 100, type: 'edge', cpu: 2, height: 1 },
    { companySize: 'middle', percent: 100, type: 'edge', cpu: 2, height: 1 },
    { companySize: 'middle', percent: 100, type: 'edge', cpu: 1, height: 0.7 },
    { companySize: 'middle', percent: 100, type: 'edge', cpu: 1, height: 0.7 },
    { companySize: 'middle', percent: 100, type: 'edge', cpu: 1, height: 0.7 },
    { companySize: 'large', percent: 100, type: 'core', cpu: 24, height: 1 },
    { companySize: 'large', percent: 100, type: 'core', cpu: 12, height: 0.5 },
    { companySize: 'large', percent: 100, type: 'small', cpu: 6 },
    { companySize: 'large', percent: 100, type: 'small', cpu: 6 },
    { companySize: 'large', percent: 100, type: 'small', cpu: 6 },
    { companySize: 'large', percent: 100, type: 'edge', cpu: 2, height: 0.67 },
    { companySize: 'large', percent: 100, type: 'edge', cpu: 2, height: 0.67 },
    { companySize: 'large', percent: 100, type: 'edge', cpu: 3, height: 1 },
    { companySize: 'large', percent: 100, type: 'edge', cpu: 3, height: 1 },
  ],
}
